using UnityEngine;

public class Gripper : MonoBehaviour
{
    public bool isObjectLocated = false;
    public Transform touchObj;

    private void OnTriggerEnter(Collider other)
    {
        if (other.tag.Contains("БнМг") || other.tag.Contains("ЧУЖѓНКЦН"))
        {
            touchObj = other.transform;
            isObjectLocated = true;
        }
    }

    private void OnTriggerExit(Collider other)
    {
        if (other.tag.Contains("БнМг") || other.tag.Contains("ЧУЖѓНКЦН"))
            isObjectLocated = false;
    }

    // TeachDataРЧ ЧіРч НКХм Сп isGripperOnРЬ TrueЖѓИщ КЮЕњШљ ЙАУМИІ РкНФ ObjectЗЮ ИИЕщБт
    public void SetChild()
    {
        if (touchObj == null) return;

        if (isObjectLocated)
        {
            touchObj.transform.SetParent(transform);
            touchObj.GetComponent<Rigidbody>().useGravity = false;
            touchObj.GetComponent<Rigidbody>().isKinematic = true;
        }
        else
        {
            touchObj.transform.SetParent(null);
            touchObj.GetComponent<Rigidbody>().useGravity = true;
            touchObj.GetComponent<Rigidbody>().isKinematic = false;
        }

    }
}
